#!/usr/bin/env python

import random
import sys

def main(numevents, starti=0):
    random.seed(0)
    processes = {}
    topo = open('topology.txt').read()
    num = 0
    for c in topo:
        if c in [' ', '\n']:
            continue
        if c in processes.keys():
            continue
        processes[num] = (c, 0)
        num = num + 1
    for i in range(starti,numevents):
        one = 0
        two = 0
        while one == two:
            one = random.randint(0, len(processes)-1)
            two = random.randint(0, len(processes)-1)
        print 'S	A	%s	%s	%s' % (processes[one][0], processes[two][0], processes[one][1])
        print 'R	A	%s	%s	%s' % (processes[one][0], processes[two][0], processes[one][1])
        processes[one] = (processes[one][0], processes[one][1] + 1)

if __name__ == '__main__':
    if len(sys.argv) > 2:
        main(int(sys.argv[1]), int(sys.argv[2]))
    else:
        main(int(sys.argv[1]))
